name: Outlast
version: ${project.version}
main: dev.dpvb.outlast.internal.OutlastPlugin
api-version: 1.19
authors: [dpvb]
description: '${project.description}'
depend:
  - ProtocolLib # Likely a required dependency
libraries:
  - cloud.commandframework:cloud-paper:${cloud.version}
  - cloud.commandframework:cloud-annotations:${cloud.version}
  - org.mongodb:mongodb-driver-sync:4.6.1